# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-06 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.IntegerField(verbose_name=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(verbose_name=128),
        ),
    ]
